### ISSUE TITLE
Server surprise sprite checklist

### ISSUE THREAD

**Issue by Probe1** [Probe1/vgstation13#7]
- [x] **Wreaths** **Dragonbro**
- [x] **Ornaments Shadowmech**
- [x] Tinsel **Dragonbro**
- [ ] Christmas stockings
- [x] **Candy canes** **Dragonbro**
- [x] **Christmas lights Blithering**
- [ ] ???

**Comment by PJB3005** [comment]
All the maps:

- [x] Box
- [x] Deff
- [x] Meta
- [ ] Christmas themed vault?

**Comment by Probe1** [comment]
We do have a Santa jetski to serve as a vault loot.

**Comment by Shadowmech88** [comment]
![candycane](https://cloud.githubusercontent.com/assets/3991927/21317307/31266b4c-c5ca-11e6-8b2d-5b6bb2f378cc.png)
Is this alright for a candy cane?
(It's the one Skullyton posted with the crook removed and the hook lengthened slightly)

**Comment by Probe1** [comment]
Yeah its fine

**Comment by Probe1** [comment]
https://a.pomf.cat/cmibjy.rar

![image](https://cloud.githubusercontent.com/assets/8550416/21321067/436fd0d8-c5e1-11e6-8f70-b2a399c64641.png)

sprites

**Comment by Shadowmech88** [comment]
Ball ornaments: http://puu.sh/sVzye/9eae7a4a25.dmi
Teardrop ornaments: http://puu.sh/sVyUm/48e64a0c64.dmi

More ornament designs may come in the following days.
